version: "3.7"
services:
    redis:
        image: redis:alpine
        command: redis-server --port 6379
        container_name: ${REDIS_CONTAINER_NAME}
        hostname: rf
        restart: always
        labels:
            - "name=redis"
            - "mode=standalone"
        ports:
            - 30000:${REDIS_PORT}
    mysql:
        image: mysql:8
        container_name: ${DB_CONTAINER_NAME}
        restart: always
        cap_add:
            - SYS_NICE
        ports:
            - 3309:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            TZ: Asia/Seoul
        # env_file:
        #     - .env
        command:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
            - --default-authentication-plugin=mysql_native_password
            - --sql-mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
        volumes:
            - ./mysql/initdb.d:/docker-entrypoint-initdb.d
            - ./dbdata:/var/lib/mysql
        healthcheck:
            test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD"]
            interval: 10s
            timeout: 2s
            retries: 100
    node:
        container_name: rf-server
        build:
            context: ./
        restart: always
        command: npm run start:dev
        ports:
            - 3000:${PORT}
        depends_on:
            mysql:
                condition: service_healthy
        environment:
            - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${DB_CONTAINER_NAME}/${MYSQL_DATABASE}
        env_file:
            - .env
        volumes:
            - ./logs:/app/logs
    caddy:
        container_name: rf-caddy
        build:
            context: ./caddy
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            # - ./site:/srv
            # - ./caddy:/etc/caddy/Caddyfile
            # - $PWD/site:/srv
            # - $PWD/caddy:/etc/caddy/Caddyfile
            - caddy_data:/data
            - caddy_config:/config

volumes:
    caddy_data:
        # external: true
    caddy_config:
